# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://l1215c1205.github.io
title: Saivian 全球首創 刷卡現金回饋20%
email: your-email@domain.com
author: Your Name
description: > # "Write an awesome description for your new site here. 
  美國大數據公司，只要提供您的刷卡消費習慣，享有信用卡現金回饋20%
#  You can edit this line in _config.yml. It will appear in your document 
#  head meta (for Google search results) and in your feed.xml site 
#  description.
copyright: 'Copyright &copy; 2016 Saivian. All Rights Reserved.'
#credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://www.facebook.com/taiwan.saivian/?fref=ts
  - title: instagram
    url: https://www.instagram.com/explore/tags/saivian/
    

